language: java
cache:
  directories:
  - $HOME/.m2
script:
  - mvn --file org.eclipse.pde.apitools.ant/pom.xml --fail-at-end test --batch-mode
  - mvn --file maven-plugins/apitools-plugin/pom.xml --fail-at-end test --batch-mode
